### ISSUE TITLE
How to extend for custom post types?

### ISSUE THREAD

**Issue by krishaamer** [julianhandl/Nextjs-Wordpress-Frontend#1]
Hi @julianhandl thank you for this fantastic starter! How would you add support for custom post type? I guess by extending the [...path] page? 

Cheers,
Kris

**Comment by julianhandl** [comment]
Yes exactly. You will have to extend the graphql query to get the template name per page and then use some if else or switch statements.

`if (result.page.template.templateName === "Project") {
			return <ProjectPage
				{...result}
				menus={menus}
				uri={props.uri}
			/>
		}
		else {
			return <PageSingle
				page={result.page}
				menus={menus}
				uri={props.uri}
			/>
		}
`
